//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//

package com.beatport.rest;

import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.client.ClientHttpRequestFactory;
import org.springframework.web.client.RestTemplate;

public class BeatportRestClient implements RestClient {

	private RestTemplate restTemplate;
	private String rootUrl;

	public BeatportRestClient() {
		restTemplate = new RestTemplate();
		rootUrl = "http://api.beatport.com";
	}

	public BeatportRestClient(RestTemplate restTemplate) {
		this.restTemplate = restTemplate;
	}

	public BeatportRestClient(ClientHttpRequestFactory requestFactory) {
		restTemplate = new RestTemplate(requestFactory);
	}

	@Override
	public void main() {
		HttpHeaders httpHeaders = new HttpHeaders();
		HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
		restTemplate.exchange(rootUrl.concat("/"), HttpMethod.GET,
				requestEntity, null).getBody();
	}

}
